SLEEP_TIME: float = 0.1
GOAL: str = 'O'
NO_GOAL: str = 'X'
HOME_GOAL: str = 'L'
AWAY_GOAL: str = 'V'
STEP: str = '-'
GOAL_PRBLTY: float = 0.03
PENALTY_DEFAULT_TURNS: int = 5
LOG_LENGTH: int = 140
GROUP_RANGE: list[str] = ['1', '2', '3', '4', '5']
GROUP_KEYS: list[str] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']