[tool.poetry]
name = "pes2020rtwc"
version = "0.1.0"
description = ""
authors = ["Juan C. Araya <jcarayacorrea@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
